---
- name: create user and create file /dir in users home dir
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"

    - name: create files/dir in home dir
      file: 
        name: "{{d}}"
        state: "{{e}}"


...
